### PR TITLE
G1 p 33 fetch contacts

### PR DESCRIPTION
**Pull request by jlehett**
**UserID with no associated contacts (No error, just empty array)**
step1

**UserID with 3 associated contacts**
step2
**_(above) Note:_** There is an "error:"" and } at the end of this like in picture 1

**Contact Database at time of testing**
step3

### CODE REVIEW

**Comment by fibster4** [comment]
Since this just returns all the contacts for a given user where are we tracking the work to search through the contacts?

**Comment by jlehett** [comment]
I forgot there was a requirement for searching contacts. I could look into passing some other parameters to the php code here to support this.

**Comment by jlehett** [comment]
**Fetch contacts with empty search string (all contacts for user)**
step1

**Fetch contacts for user with no contacts and empty search string**
step4

**Fetch contacts for user 1 with search string detecting "67" in any field**
step2

**Fetch contacts for user 1 with search string detecting "York" in any field**
step3

**Comment by fibster4** [comment]
I think this is good, so you've got my approval to merge!

I do think it's worth looking a little bit more into the search functionality though (not as a part of this task). For instance if we were to try to search for "Firstname Lastname" the search won't return anything (I think).

**Pull request merged**
