### PR TITLE
G1 p 35 link sign up page to api

### PR DESCRIPTION
**Pull request by Boissineau**
Finished the link from register.html to the API. You can now create accounts and have it sent to the database. 

image

Errors work as well. 
image

### CODE REVIEW

**Comment by fibster4** [comment]
Looks good. Does the password confirmation field do anything? Do you think we should add some input validation on the email as well? (i.e throw an error if the email isn't well formatted, I'm sure someone has a handy regex you could use for this if you think it would be a good addition)

**Comment by Boissineau** [comment]
Password confirmation does nothing at the moment, but it's an easy enough thing to implement. Email validation can be done as well. I'll create a new JIRA task to get these done or I'll add it to an upcoming task to get done later.

**Comment by fibster4** [comment]
Sounds good to push this then! If you could do squash and merge that'd be awesome too lol

**Comment by Boissineau** [comment]
I stopped being lazy and added the password and email validation to this branch. Didn't want to bother doing it later.

**Comment by jlehett** [comment]
Yep, looks good to me. I pulled that branch over to AWS to test it, and everything seems to be working correctly.
A couple things I noticed that we'll have to polish up later though:

- We should probably have a header on the card for "Login" and "Register" (or "Sign Up"). When redirecting from the register page to the login page, it's hard to tell that it's changed. The sign in / register button at the bottom isn't enough in my opinion.
- We'll also need to work on polishing up the experience on smaller screens. Using responsive view on chrome, the card gets squished a little too much. We'll have to use media queries in the CSS or html to change the margins once the screen reaches a certain width.

Those things will be tracked in a later JIRA task though that I'll create. Overall, looks good! Approved!

**Pull request merged**
